"""init all database tables

Revision ID: 01567330d015
Revises: 1a346db0c03e
Create Date: 2026-06-10 05:23:48.918959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '01567330d015'
down_revision: Union[str, None] = '1a346db0c03e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_assignment_submissions_submission_id', table_name='assignment_submissions')
    op.drop_table('assignment_submissions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignment_submissions',
    sa.Column('submission_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('assignment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('link_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('file_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('submitted_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.assignment_id'], name='assignment_submissions_assignment_id_fkey'),
    sa.ForeignKeyConstraint(['student_id'], ['users.user_id'], name='assignment_submissions_student_id_fkey'),
    sa.PrimaryKeyConstraint('submission_id', name='assignment_submissions_pkey')
    )
    op.create_index('ix_assignment_submissions_submission_id', 'assignment_submissions', ['submission_id'], unique=False)
    # ### end Alembic commands ###
