"""init all database tables

Revision ID: 01e136d5ae51
Revises: 0f687779851f
Create Date: 2026-06-09 04:12:10.280025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '01e136d5ae51'
down_revision: Union[str, None] = '0f687779851f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_device_tokens_id', table_name='device_tokens')
    op.drop_table('device_tokens')
    op.drop_index('ix_app_notifications_id', table_name='app_notifications')
    op.drop_table('app_notifications')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_notifications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('body', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('notif_type', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('ref_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='app_notifications_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='app_notifications_pkey')
    )
    op.create_index('ix_app_notifications_id', 'app_notifications', ['id'], unique=False)
    op.create_table('device_tokens',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('platform', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='device_tokens_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='device_tokens_pkey'),
    sa.UniqueConstraint('token', name='device_tokens_token_key')
    )
    op.create_index('ix_device_tokens_id', 'device_tokens', ['id'], unique=False)
    # ### end Alembic commands ###
