"""add reply_to_id to chat_history

Revision ID: 1a9021efb576
Revises: 583546edc9cb
Create Date: 2026-05-25 23:52:11.681541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a9021efb576'
down_revision: Union[str, None] = '583546edc9cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_history', sa.Column('reply_to_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'chat_history', 'chat_history', ['reply_to_id'], ['chat_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_history', type_='foreignkey')
    op.drop_column('chat_history', 'reply_to_id')
    # ### end Alembic commands ###
