"""add is_deleted and edited_at to chat_history

Revision ID: 2a1baa9a368b
Revises: 7e865fb6dd37
Create Date: 2026-05-25 15:50:38.314199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a1baa9a368b'
down_revision: Union[str, None] = '7e865fb6dd37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_history', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('chat_history', sa.Column('edited_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_history', 'edited_at')
    op.drop_column('chat_history', 'is_deleted')
    # ### end Alembic commands ###
