"""add_file_size_to_material_files

Revision ID: 37406f532763
Revises: 6196a35ed4cb
Create Date: 2026-05-27 18:15:14.550047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37406f532763'
down_revision: Union[str, None] = '6196a35ed4cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('material_files', sa.Column('file_size', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('material_files', 'file_size')
    # ### end Alembic commands ###
