"""fix_material_department_course

Revision ID: 475c1ee63616
Revises: 9d2ceabed6bb
Create Date: 2026-05-26 21:48:11.471420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '475c1ee63616'
down_revision: Union[str, None] = '9d2ceabed6bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('material', sa.Column('department_course', sa.String(length=10), nullable=False, server_default='general'))
    op.alter_column('material', 'department_course', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('material', 'department_course')
    # ### end Alembic commands ###
