"""add chat tables

Revision ID: 54c488750c72
Revises: c8b51ec7c7d4
Create Date: 2026-05-25 02:49:50.239730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '54c488750c72'
down_revision: Union[str, None] = 'c8b51ec7c7d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_complaints_complaint_id', table_name='complaints')
    op.drop_table('complaints')
    op.alter_column('assignments', 'material_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.create_foreign_key(None, 'assignments', 'material', ['material_id'], ['material_id'])
    op.alter_column('material_files', 'material_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.create_foreign_key(None, 'material_files', 'material', ['material_id'], ['material_id'])
    op.add_column('users', sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_seen')
    op.drop_constraint(None, 'material_files', type_='foreignkey')
    op.alter_column('material_files', 'material_id',
               existing_type=sa.String(length=10),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_constraint(None, 'assignments', type_='foreignkey')
    op.alter_column('assignments', 'material_id',
               existing_type=sa.String(length=10),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.create_table('complaints',
    sa.Column('complaint_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('material_id', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('complaint_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('send_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['material.material_id'], name='complaints_material_id_fkey'),
    sa.ForeignKeyConstraint(['student_id'], ['users.user_id'], name='complaints_student_id_fkey'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.user_id'], name='complaints_teacher_id_fkey'),
    sa.PrimaryKeyConstraint('complaint_id', name='complaints_pkey')
    )
    op.create_index('ix_complaints_complaint_id', 'complaints', ['complaint_id'], unique=False)
    # ### end Alembic commands ###
