"""add file_type to chat_history

Revision ID: 943979c64c12
Revises: 28a6bd7dc435
Create Date: 2026-05-25 15:27:40.312391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '943979c64c12'
down_revision: Union[str, None] = '28a6bd7dc435'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_history', sa.Column('file_type', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_history', 'file_type')
    # ### end Alembic commands ###
