"""remove department_course from material

Revision ID: 9f5290e53baa
Revises: bd47b9ca2f1a
Create Date: 2026-05-28 03:27:30.196537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f5290e53baa'
down_revision: Union[str, None] = 'bd47b9ca2f1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('material', 'department_course')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('material', sa.Column('department_course', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
