"""add_target_role_and_nullable_material_id

Revision ID: bd47b9ca2f1a
Revises: 37406f532763
Create Date: 2026-05-28 01:06:52.132753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd47b9ca2f1a'
down_revision: Union[str, None] = '37406f532763'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('announcements', sa.Column('target_role', sa.String(length=10), nullable=True))
    op.alter_column('material_files', 'material_id',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('material_files', 'material_id',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.drop_column('announcements', 'target_role')
    # ### end Alembic commands ###
