"""merge message_type and file_type into content_type

Revision ID: c1bbe9443285
Revises: 4bf3bfb2ba06
Create Date: 2026-05-25 15:41:32.093104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1bbe9443285'
down_revision: Union[str, None] = '4bf3bfb2ba06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_history', sa.Column('content_type', sa.String(length=20), nullable=False))
    op.drop_column('chat_history', 'file_type')
    op.drop_column('chat_history', 'message_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_history', sa.Column('message_type', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.add_column('chat_history', sa.Column('file_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_column('chat_history', 'content_type')
    # ### end Alembic commands ###
